version: "3.9"

services:
  backend:
    build: ./UrlFetcherService
    ports:
      - "8080:8080"

  frontend:
    build: ./url-fetcher-app
    ports:
      - "3000:3000"
    depends_on:
      - backend